[package]
name = "admin/03"
version = "0.1.0"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[dependencies]
React = "jsdotlua/react@17.2.1"
ReactRoblox = "jsdotlua/react-roblox@17.2.1"
Charm = "littensy/charm@0.10.0"
Ripple = "littensy/ripple@0.10.1"
ReactCharm = "littensy/react-charm@0.3.0"